services:
  # Serviço do Banco de Dados
  arcoportus_db:
    image: postgres:15-alpine
    container_name: arcoportus_postgres_db
    restart: always
    env_file:
      - ./.env # Carrega as variáveis do nosso arquivo .env
    ports:
      - "${DB_PORT}:5432" # Usa a porta definida no .env
    volumes:
      - arcoportus-data:/var/lib/postgresql/data
    networks:
      - arcoportus-net

  # Serviço do Backend
  arcoportus_backend:
    container_name: arcoportus_backend_api
    build:
      context: . # Constrói a imagem usando o Dockerfile na pasta atual (backend/)
    restart: always
    env_file:
      - ./.env
    ports:
      - "${BACKEND_PORT}:3334"
    volumes:
      - ./src:/app/src # Monta o código-fonte para hot-reloading
    depends_on:
      - arcoportus_db # Garante que o DB inicie antes do backend
    networks:
      - arcoportus-net

  # Serviço do Frontend
  arcoportus_frontend:
    container_name: arcoportus_frontend_ui
    build:
      context: ../frontend # Constrói a imagem usando o Dockerfile na pasta frontend/
    restart: always
    ports:
      - "${FRONTEND_PORT}:5174"
    volumes:
      - ../frontend/src:/app/src # Monta o código-fonte para hot-reloading
    depends_on:
      - arcoportus_backend
    networks:
      - arcoportus-net

volumes:
  arcoportus-data:
    driver: local

networks:
  arcoportus-net:
    driver: bridge