# ./docker-compose.yml

version: '3.8'

services:
  # Serviço do Banco de Dados PostgreSQL
  postgres:
    image: postgres:16-alpine
    container_name: cga_postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - cga_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  # Serviço do Backend (Node.js/Express/Prisma)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev # Usaremos um Dockerfile específico para desenvolvimento
    container_name: cga_backend_api
    ports:
      - "3333:3333" # Porta da API
    volumes:
      - ./backend:/usr/app
      - /usr/app/node_modules # Evita que o node_modules local sobrescreva o do container
    depends_on:
      - postgres
    environment:
      DATABASE_URL: ${DATABASE_URL}
      # Outras variáveis de ambiente (JWT_SECRET, etc)
    restart: unless-stopped

  # Serviço do Frontend (React/Vite)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: cga_frontend_app
    ports:
      - "5173:5173" # Porta padrão do Vite
    volumes:
      - ./frontend:/usr/app
      - /usr/app/node_modules
    restart: unless-stopped

volumes:
  cga_postgres_data: